name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    env:
      CC: gcc-14
      CXX: g++-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
        cmake --version
        $CC --version
        $CXX --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build binary
      run: cmake --build ${{github.workspace}}/build --target vgraph

    - name: Build unit tests
      run: cmake --build ${{github.workspace}}/build --target vgraph_test

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ./vgraph_test
