name: Build binary

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
        cmake --version
        gcc --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build binary
      run: cmake --build ${{github.workspace}}/build --target vgraph
