name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build binary
      run: cmake --build ${{github.workspace}}/build --target vgraph

    - name: Build unit tests
      run: cmake --build ${{github.workspace}}/build --target vgraph_test

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ./vgraph_test
